name: Python build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Upgrade pip and tools
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install package and dependencies
      run: pip install .[test]
    - name: Run the test
      run: python -m unittest discover -s test
      env:
        MERCHANT_CODE: ${{ secrets.MERCHANT_CODE }}
        API_KEY: ${{ secrets.API_KEY }}